version: '3'

services:
  app:
    image: chatlogin3 # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatlogin3
    restart: unless-stopped
    ports:
      - 9070:3002
    environment:
      TZ: Asia/Shanghai
      # 二选一
      OPENAI_API_KEY: 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
      # 二选一
      OPENAI_ACCESS_TOKEN:
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: http://chatapi.a3r.cn
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: 
      # 反向代理，可选
      API_REVERSE_PROXY:
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY: www
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 1000000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: 
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: 
      # Socks代理用户名，可选，和 SOCKS_PROXY_HOST & SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_USERNAME:
      # Socks代理密码，可选，和 SOCKS_PROXY_HOST & SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_PASSWORD:
      # HTTPS_PROXY 代理，可选
      HTTPS_PROXY: 
      # 网站名称
      SITE_TITLE: ChatGpt
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://chatgpt:123456@172.22.0.1:9042'
      # 网站是否开启注册
      REGISTER_ENABLED: "true"
      REGISTER_REVIEW: "false"
      RETRY_INTERVAL_MS: 1000

      # 开启注册之后 网站注册允许的邮箱后缀 如果空 则允许任意后缀
      REGISTER_MAILS: '@qq.com,@sina.com,@163.com'
      # 开启注册之后 密码加密的盐
      PASSWORD_MD5_SALT: anysalt
      # 开启注册之后 超级管理邮箱
      ROOT_USER: 1243076446@qq.com
      # 开启注册之后 网站域名 不含 / 注册的时候发送验证邮箱使用
      SITE_DOMAIN: https://1chat.cc
      # 开启注册之后 发送验证邮箱配置
      SMTP_HOST: smtp.qq.com
      SMTP_PORT: 587
      SMTP_TSL: "false"
      SMTP_USERNAME: 2424123787@qq.com
      SMTP_PASSWORD: hpycqnivahffdiaj
      # 是否开启敏感词审核, 因为响应结果是流式 所以暂时没审核
      AUDIT_ENABLED: "false"
      # https://ai.baidu.com/ai-doc/ANTIPORN/Vk3h6xaga
      AUDIT_PROVIDER: baidu
      AUDIT_API_KEY: 
      AUDIT_API_SECRET:
      AUDIT_TEXT_LABEL:
   

 

volumes:
  mongodb: {}
